spring.application.name=ems
# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ems
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8092
# Redis Configuration
spring.redis.host=localhost
spring.redis.port=6379